version: "3"

services:
    frontend:
        build: ./frontend
        ports:
            - "80:80"
        volumes:
            - "./frontend:/app"
    backend:
        build: ./backend
        ports:
            - "3033:3033"
        volumes:
            - "./backend:/app"
        depends_on:
            - db
        environment:
            # Ativar modo "produção" para uso da build em /dist.
            # No development é gerenciado por nodemon.
            - NODE_ENV=development
    db:
        build: ./postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: facilita
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
